#! /nfs/apps/python/2.6.5/bin/python 
import sys
import immgen
import logging

logging.basicConfig(stream=sys.stdout,level=logging.INFO)

def usage():
	u = """\n\n preprocess_immgen_data root_folder GEOid outfile
	
	Preprocesses a set of CEL files stored using the aroma file structure,
	starting at root_folder. Stores all data, including the outfile, in
	<root_folder>/userData/<GEOid>/
	
	Parameters
	==========
	root_folder : path
		where your data is stored (or will be stored)
	GEOid : GEO accession ID (optional)
		GEO accession ID of the data set you'd like to preprocess
	outfile : filename (optional)
		name of the file in which to store the expression set object
	
	Returns
	=======
	A Bioconductor "ExpressionSet" object which is stored in 
	<root_folder>/userData/<GEOid>/<outfile>
	
	Notes
	=====
	The default GEOid is the immgen data set GSE15907 and the default outfile
	name is "immgen.data". 
	
	WARNING : you need to populate 
	<root_folder>anotationData/chipTypes/<chip_folder>/ manually!
	
	TODO
	====
	If you want to specify a new name for the outfile then you also need to 
	specify the GEOid. I know this is rubbish, and I'll	update the script to 
	use getopts or something at some point.
	
	Example
	=======
	./preprocess_immgen_data /Users/mike/Data/Test
	"""
	print u

try:
	root_folder = sys.argv[1]
	if root_folder in ["-h","--help"]:
		usage()
		sys.exit()
except IndexError:
	usage()
	raise ValueError("you must specify a root folder")

try:
	GEOid = sys.argv[2]
	outfile = sys.argv[3]
except IndexError:
	immgen.preprocess(root_folder)
else:
	immgen.preprocess(root_folder,GEOid,outfile)
